services:
    minio:
        ports:
            - 9000:9000
            - 9001:9001
        container_name: minio
        restart: unless-stopped
        volumes:
            - ~/minio/data:/data
        environment:
            MINIO_ROOT_USER: ${MINIO_ROOT_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        image: quay.io/minio/minio
        command: server /data --console-address ":9001"	
    postgres:
        image: postgres:15
        container_name: iot_postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
   
volumes: 
    postgres_data:
